config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  devise_scope :user do
    root to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  get :guidelines, to: 'pages#guidelines'
  resources :feedbacks, path: :feedback do
    member do
      patch :add_reply
    end
  end
  get 'dashboards', to: 'proposal_types#index'

  resources :submitted_proposals do
    collection do
      get :download_csv
      post :edit_flow
    end
    member do
      post :staff_discussion
      post :send_emails
      post :approve_status
      post :decline_status
    end
  end

  get :invite, to: 'invites#show'
  get 'expired' => 'invites#expired'
  post 'cancel' => 'invites#cancel'

  resources :proposals do
    post :latex, to: 'proposals#latex_input'
    member do
      get :rendered_proposal, to: 'proposals#latex_output'
      get :rendered_field, to: 'proposals#latex_field'
      patch :ranking
      get :locations
      post :upload_file
      post :remove_file
    end

    resources :invites, except: [:show] do
      member do
        post :inviter_response
        post :invite_reminder
        post :invite_email
      end
      collection do
        get :thanks
      end
    end
  end

  resources :survey do
    collection do
      get :survey_questionnaire
      get :faqs
      post :submit_survey
    end
  end

  resources :people, path: :person

  resources :submit_proposals do
    collection do
      get :thanks
    end
  end
  resources :proposal_types do
    resources :proposal_forms do
      member do
        post :clone
        delete :proposal_field
        get :proposal_field_edit
      end
      resources :proposal_fields do
        collection do
          post :latex_text
        end
      end
    end
    member do
      get :location_based_fields
      get :proposal_type_locations
    end
  end
  resources :locations do
    member do
      get :proposal_types
    end
  end
  resources :page_contents

  resources :faqs do
    member do
      patch :move
    end
  end

  get 'profile/' => 'profile#edit'
  patch 'update' => 'profile#update'
  post 'demographic_data' => 'profile#demographic_data'

  resources :roles do
    member do
      post :new_user
      post :new_role
      post :remove_role
    end
  end

  resources :subject_categories do
    resources :subjects
    resources :ams_subjects
  end

  resources :emails do
    collection do
      patch :email_template
    end
  end

  resources :email_templates
end

app/models/faq.rb
class Faq < ApplicationRecord
  validates :question, :answer, presence: true
  has_rich_text :answer
  acts_as_list
  default_scope { order(position: :asc) }
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  load_and_authorize_resource
  before_action :set_faq, only: %i[edit update destroy move]
  before_action :require_staff_member

  def index
    @faqs = Faq.all
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(faq_params)
    if @faq.save
      redirect_to faqs_path, notice: 'Your faq has been saved.'
    else
      render :new, alert: 'There is error while saving faq.'
    end
  end

  def edit; end

  def update
    redirect_to faqs_path, notice: "Faq has been updated!" if @faq.update(faq_params)
  end

  def destroy
    redirect_to faqs_path, notice: "Faq has been deleted!" if @faq.destroy
  end

  def move
    @faq = Faq.find_by(id: params[:faq_id])
    @faq.update(position: params[:position].to_i)
    head :ok
  end

  private

  def set_faq
    @faq = Faq.find(params[:id])
  end

  def faq_params
    params.require(:faq).permit(:question, :answer)
  end

  def require_staff_member
    redirect_to root_path unless current_user.staff_member?
  end
end

app/views/faqs/_form.html.erb
<main class="content">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        FAQs
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><%= link_to "FAQs", faqs_path %></li>
          <li class="breadcrumb-item active" aria-current="page">New</li>
        </ol>
      </nav>
    </div>
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title"> </h5>
        </div>
        <div class="card-body">
          <%= form_for @faq do |f| %>
            <div class="mb-3">
              <h2>FAQ</h2>
              <p>Add a new frequently asked question here</p>
              <%= f.text_area(:question, required: true, size: '3x3', class:'form-control mb-4', placeholder: "Write question here...")%>
              <%= f.text_area(:answer, required: true, size: '3x5', class:'form-control', placeholder: "Write answer here...")%>
            </div>
            <%= f.submit @faq.new_record? ? "Create" : "Update", class:  'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/faqs/edit.html.erb
<%= render 'form', faq: @faq %>

app/views/faqs/index.html.erb
<main class="content" style="overflow-x: auto">
<div class="container-fluid">
<div class="header">
  <h1 class="header-title">
    Frequently Asked Questions
  </h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><%= link_to "FAQs", faqs_path %></li>
    </ol>
  </nav>
</div>
<div class="col-12">
  <div class="card">
  	<div class="card-header">
      <div class="mb-3 d-flex justify-content-between">
	      <h3>FAQs</h3>
	      <div class="float-end">
	        <%= link_to "Add FAQ", new_faq_url, class: "btn btn-lg btn-primary" %>
	      </div>
	    </div>
    </div>
    <div data-controller="drag">
      <% @faqs.order(position: :asc).each do |faq| %>
        <div class="card-body cursor-pointer" data-id="<%= faq.id %>">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title mb-0"><%= faq.question&.html_safe %></h3>
            </div>
            <div class="card-body">
              <%= faq.answer %>
            </div>
            <div class="text-end m-2">
              <%= link_to 'Edit', edit_faq_url(faq.id), class: "btn btn-primary" %>
              <%= link_to 'Delete', faq_path(faq.id), method: :delete , data: {confirm: "Are you sure you want to delete this field?"}, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/faqs/new.html.erb
<%= render 'form', faq: @faq %>