config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  devise_scope :user do
    root to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  get :guidelines, to: 'pages#guidelines'
  resources :feedbacks, path: :feedback do
    member do
      patch :add_reply
    end
  end
  get 'dashboards', to: 'proposal_types#index'

  resources :submitted_proposals do
    collection do
      get :download_csv
      post :edit_flow
    end
    member do
      post :staff_discussion
      post :send_emails
      post :approve_status
      post :decline_status
    end
  end

  get :invite, to: 'invites#show'
  get 'expired' => 'invites#expired'
  post 'cancel' => 'invites#cancel'

  resources :proposals do
    post :latex, to: 'proposals#latex_input'
    member do
      get :rendered_proposal, to: 'proposals#latex_output'
      get :rendered_field, to: 'proposals#latex_field'
      patch :ranking
      get :locations
      post :upload_file
      post :remove_file
    end

    resources :invites, except: [:show] do
      member do
        post :inviter_response
        post :invite_reminder
        post :invite_email
      end
      collection do
        get :thanks
      end
    end
  end

  resources :survey do
    collection do
      get :survey_questionnaire
      get :faqs
      post :submit_survey
    end
  end

  resources :people, path: :person

  resources :submit_proposals do
    collection do
      get :thanks
    end
  end
  resources :proposal_types do
    resources :proposal_forms do
      member do
        post :clone
        delete :proposal_field
        get :proposal_field_edit
      end
      resources :proposal_fields do
        collection do
          post :latex_text
        end
      end
    end
    member do
      get :location_based_fields
      get :proposal_type_locations
    end
  end
  resources :locations do
    member do
      get :proposal_types
    end
  end
  resources :page_contents

  resources :faqs do
    member do
      patch :move
    end
  end

  get 'profile/' => 'profile#edit'
  patch 'update' => 'profile#update'
  post 'demographic_data' => 'profile#demographic_data'

  resources :roles do
    member do
      post :new_user
      post :new_role
      post :remove_role
    end
  end

  resources :subject_categories do
    resources :subjects
    resources :ams_subjects
  end

  resources :emails do
    collection do
      patch :email_template
    end
  end

  resources :email_templates
end

app/controllers/submitted_proposals_controller.rb
class SubmittedProposalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_proposals, only: %i[index download_csv]
  before_action :set_proposal, except: %i[index download_csv]

  def index; end

  def show; end

  def download_csv
    send_data @proposals.to_csv, filename: "submitted_proposals.csv"
  end

  def edit_flow
    params[:ids]&.split(',')&.each do |id|
      @proposal = Proposal.find_by(id: id.to_i)
      post_to_editflow
    end

    respond_to do |format|
      format.js { render js: "window.location='/submitted_proposals'" }
      format.html { redirect_to submitted_proposals_path, notice: 'Successfully sent proposal(s) to EditFlow!' }
    end
  end

  def staff_discussion
    return unless @ability.can?(:manage, Email)

    @staff_discussion = StaffDiscussion.new
    discussion = params[:discussion]
    if @staff_discussion.update(discussion: discussion,
                                proposal_id: @proposal.id)
      redirect_to submitted_proposal_url(@proposal),
                  notice: "Your comment was added!"
    else
      redirect_to submitted_proposal_url(@proposal),
                  alert: @staff_discussion.errors.full_messages
    end
  end

  def send_emails
    return unless @ability.can?(:manage, Email)

    @email = Email.new(email_params.merge(proposal_id: @proposal.id))
    if @email.save
      @email.email_organizers
      redirect_to submitted_proposal_url(@proposal),
                  notice: "Sent email to proposal organizers."
    else
      redirect_to submitted_proposal_url(@proposal),
                  alert: @email.errors.full_messages
    end
  end

  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html do
        redirect_to submitted_proposals_url,
                    notice: "Proposal was successfully deleted."
      end
      format.json { head :no_content }
    end
  end

  def approve_status
    @proposal.update(status: 'approved')
    redirect_to submitted_proposals_url(@proposal),
                notice: "Proposal has been approved."
  end

  def decline_status
    @proposal.update(status: 'declined')
    redirect_to submitted_proposals_url(@proposal),
                notice: "Proposal has been declined."
  end

  private

  def query_params?
    params.values.any?(&:present?)
  end

  def email_params
    params.permit(:subject, :body, :revision)
  end

  def set_proposals
    @proposals = Proposal.order(:created_at)
    @proposals = ProposalFiltersQuery.new(@proposals).find(params) if query_params?
  end

  def latex_temp_file
    "propfile-#{current_user.id}-#{@proposal.id}.tex"
  end

  def create_pdf_file
    prop_pdf = ProposalPdfService.new(@proposal.id, latex_temp_file, 'all')
    prop_pdf.pdf

    @year = @proposal&.year || Date.current.year.to_i + 2
    pdf_file = render_to_string layout: "application",
                                inline: prop_pdf.to_s, formats: [:pdf]

    @pdf_path = "#{Rails.root}/tmp/submit-#{DateTime.now.to_i}.pdf"
    File.open(@pdf_path, "w:UTF-8") do |file|
      file.write(pdf_file)
    end
  end

  def post_to_editflow
    create_pdf_file

    query_edit_flow = EditFlowService.new(@proposal).query

    response = RestClient.post ENV['EDITFLOW_API_URL'],
                               { query: query_edit_flow, fileMain: File.open(@pdf_path) },
                               { x_editflow_api_token: ENV['EDITFLOW_API_TOKEN'] }
    puts response

    if response.body.include?("errors")
      Rails.logger.debug { "\n\n*****************************************\n\n" }
      Rails.logger.debug { "EditFlow POST error:\n #{response.body.inspect}\n" }
      Rails.logger.debug { "\n\n*****************************************\n\n" }
      flash[:alert] = "Error sending data!"
    else
      flash[:notice] = "Data sent to EditFlow!"
      @proposal.update(edit_flow: Time.zone.now)
    end
  end

  def set_proposal
    @proposal = Proposal.find_by(id: params[:id])
  end
end

app/helpers/submitted_proposals_helper.rb
module SubmittedProposalsHelper
  def all_proposal_types
    ProposalType.all.map { |pt| [pt.name, pt.id] }
  end

  def submitted_graph_data(param, param2, proposals)
    data = Hash.new(0)
    proposals&.each do |proposal|
      citizenships = proposal.demographics_data.pluck(:result)
                             .pluck(param, param2).flatten.reject do |s|
        s.blank? || s.eql?("Other")
      end

      citizenships.each do |c|
        data[c] += 1
      end
    end
    data
  end

  def submitted_nationality_data(proposals)
    submitted_graph_data("citizenships", "citizenships_other", proposals)
  end

  def submitted_ethnicity_data(proposals)
    submitted_graph_data("ethnicity", "ethnicity_other", proposals)
  end

  def submitted_gender_labels(proposals)
    data = submitted_graph_data("gender", "gender_other", proposals)
    data.keys
  end

  def submitted_gender_values(proposals)
    data = submitted_graph_data("gender", "gender_other", proposals)
    data.values
  end

  # rubocop:disable Metrics/AbcSize
  def submitted_career_data(param, param2, proposals)
    data = Hash.new(0)
    proposals&.each do |proposal|
      person = Person.where.not(id: proposal.lead_organizer&.id)
      career_stage = person.where(id: proposal.person_ids).pluck(param, param2)
                           .flatten.reject do |s|
        s.blank? || s.eql?("Other")
      end

      career_stage.each do |s|
        data[s] += 1
      end
    end
    data
  end

  # rubocop:enable Metrics/AbcSize
  def submitted_career_labels(proposals)
    data = submitted_career_data("academic_status", "other_academic_status",
                                 proposals)
    data.keys
  end

  def submitted_career_values(proposals)
    data = submitted_career_data("academic_status", "other_academic_status",
                                 proposals)
    data.values
  end

  def submitted_stem_graph_data(proposals)
    data = Hash.new(0)
    proposals&.each do |proposal|
      citizenships = proposal.demographics_data.pluck(:result).pluck("stem").flatten.reject do |s|
        s.blank? || s.eql?("Other")
      end

      citizenships.each do |c|
        data[c] += 1
      end
    end
    data
  end

  def submitted_stem_labels(proposals)
    data = submitted_stem_graph_data(proposals)
    data.keys
  end

  def submitted_stem_values(proposals)
    data = submitted_stem_graph_data(proposals)
    data.values
  end

  def organizers_email(proposal)
    proposal.invites.where(invited_as: 'Organizer').map(&:person).map(&:email).join(', ')
  end
end

app/views/submitted_proposals/_birs_discussion.html.erb
<div>
  <%= form_with(url: birs_discussion_submitted_proposal_path(@proposal), method: :post) do |f| %>
    <div class="mb-3">
      <h4>Discussion:</h4>
      <%=f.text_area(:discussion, required: true, size: '3x5', class:'form-control')%>
    </div>
    <button class="btn btn-primary">Submit</button>
  <% end %>
</div>
<br />
<div class="mt-4">
  <h2> Discussions </h2>
  <% BirsDiscussion.all&.each do |birs| %>
    <div class="mt-4">
      <p class="form-control"><%= birs.discussion %></p>
    </div>
  <% end %>
</div>

app/views/submitted_proposals/_demographic_charts.html.erb
<div>
  <div class="mb-3">Charts</div>

  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="card flex-fill w-100">
        <div class="card-header">
          <h5 class="card-title">Nationality</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Nationality</th>
                <th>No.</th>
              </tr>
            </thead>
            <tbody>
              <% submitted_nationality_data(@proposals).each do |key, value| %>
              <tr>
                <td><%= key %></td>
                <td><%=  value %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="card flex-fill w-100">
        <div class="card-header">
          <h5 class="card-title">Ethnicity</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Ethnicity</th>
                <th>No.</th>
              </tr>
            </thead>
            <tbody>
              <% submitted_ethnicity_data(@proposals).each do |key, value| %>
              <tr>
                <td><%= key %></td>
                <td><%=  value %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="card flex-fill w-100">
        <div class="card-header">
          <h5 class="card-title">Gender</h5>
          <!-- <h6 class="card-subtitle text-muted">A line chart is a way of plotting data points on a line.</h6> -->
        </div>
        <div class="card-body">
          <div class="chart">
            <canvas id="chartjs-gender"></canvas>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="card flex-fill w-100">
        <div class="card-header">
          <h5 class="card-title">Under-represented minority in STEM</h5>
          <!-- <h6 class="card-subtitle text-muted">A line chart is a way of plotting data points on a line.</h6> -->
        </div>
        <div class="card-body">
          <div class="chart">
            <canvas id="chartjs-stem"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="card flex-fill w-100">
        <div class="card-header">
          <h5 class="card-title">Career Stage</h5>
        </div>
        <div class="card-body">
          <div class="chart">
            <canvas id="chartjs-career"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <script>
  document.addEventListener("DOMContentLoaded", function() {
    new Chart(document.getElementById("chartjs-gender"), {
      type: "bar",
      data: {
        labels: <%= submitted_gender_labels(@proposals).to_json.html_safe %>,
        datasets: [{
          fill: true,
          backgroundColor: "rgba(50, 83, 168)",
          borderColor: window.theme.primary,
          data: <%= submitted_gender_values(@proposals) %>
        }]
      },
      options: {
        maintainAspectRatio: false,
        legend: {
          display: false
        },
        tooltips: {
          intersect: false
        },
        hover: {
          intersect: true
        },
        plugins: {
          filler: {
            propagate: false
          }
        },
        scales: {
          xAxes: [{
            reverse: true,
            gridLines: {
              color: "rgba(0,0,0,0.05)"
            }
          }],
          yAxes: [{
            ticks: {
              stepSize: 500
            },
            display: true,
            borderDash: [5, 5],
            gridLines: {
              color: "rgba(0,0,0,0)",
              fontColor: "#fff"
            }
          }]
        }
      }
    });

    new Chart(document.getElementById("chartjs-stem"), {
      type: "bar",
      data: {
        labels: <%= submitted_stem_labels(@proposals).to_json.html_safe %>,
        datasets: [{
          fill: true,
          backgroundColor: "rgba(50, 83, 168)",
          borderColor: window.theme.primary,
          data: <%= submitted_stem_values(@proposals) %>
        }]
      },
      options: {
        maintainAspectRatio: false,
        legend: {
          display: false
        },
        tooltips: {
          intersect: false
        },
        hover: {
          intersect: true
        },
        plugins: {
          filler: {
            propagate: false
          }
        },
        scales: {
          xAxes: [{
            reverse: true,
            gridLines: {
              color: "rgba(0,0,0,0.05)"
            }
          }],
          yAxes: [{
            ticks: {
              stepSize: 500
            },
            display: true,
            borderDash: [5, 5],
            gridLines: {
              color: "rgba(0,0,0,0)",
              fontColor: "#fff"
            }
          }]
        }
      }
    });

    new Chart(document.getElementById("chartjs-career"), {
      type: "bar",
      data: {
        labels: <%= submitted_career_labels(@proposals).to_json.html_safe %>,
        datasets: [{
          fill: true,
          backgroundColor: "rgba(50, 83, 168)",
          borderColor: window.theme.primary,
          data: <%= submitted_career_values(@proposals) %>
        }]
      },
      options: {
        maintainAspectRatio: false,
        legend: {
          display: false
        },
        tooltips: {
          intersect: false
        },
        hover: {
          intersect: true
        },
        plugins: {
          filler: {
            propagate: false
          }
        },
        scales: {
          xAxes: [{
            reverse: true,
            gridLines: {
              color: "rgba(0,0,0,0.05)"
            }
          }],
          yAxes: [{
            ticks: {
              stepSize: 500
            },
            display: true,
            borderDash: [5, 5],
            gridLines: {
              color: "rgba(0,0,0,0)",
              fontColor: "#fff"
            }
          }]
        }
      }
    });
  });
</script>

app/views/submitted_proposals/_proposals.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Code</th>
      <th>Proposal Title</th>
      <th>Proposal Type</th>
      <th>Lead Organizer</th>
      <th>Preferred Location</th>
      <th>Status</th>
      <th width="125">Updated</th>
      <th>Submitted to EditFlow</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @proposals&.each do |proposal| %>
    <tr>
      <td><input type="checkbox"  name="reviewed" data-value="<%= proposal.id %>"></td>
      <td><%= proposal.code %></td>
      <td><%= proposal.title %></td>
      <td><%= proposal.proposal_type.name %></td>
      <td><%= proposal.lead_organizer&.fullname %></td>
      <td> 
        <% proposal.locations.each do |loc| %>
         <%= loc.name %><br>
        <% end %>
      </td>
      <td class=<%= proposal_status_class(proposal.status) %> >
        <%= proposal.status&.split('_')&.map(&:capitalize)&.join(' ') %>
      </td>
      <td><%= proposal.updated_at.to_date %></td>
      <td><%= proposal.edit_flow %></td>
      <td class="table-action">
        <%= link_to '<i class="align-middle fas fa-fw fa-print"></i>PDF'.html_safe, rendered_proposal_proposal_path(proposal.id, :format => :pdf), target: '_blank' %>
        <%= link_to '<i class="align-middle fas fa-fw fa-eye"></i>Show'.html_safe, submitted_proposal_url(proposal) %>
        <%= link_to '<i class="align-middle fas fa-fw fa-trash" data-toggle="tooltip" title="Delete" ></i>Delete'.html_safe,submitted_proposal_url(proposal), method: :delete , data: {confirm: "Are you sure you want to delete this proposal?"} %>
        <%= link_to '<i class="align-middle fas fa-fw fa-check"></i>Approve'.html_safe, approve_status_submitted_proposal_url(proposal), method: :post %>
        <%= link_to '<i class="align-middle fas fa-fw fa-times"></i>Decline'.html_safe, decline_status_submitted_proposal_url(proposal), method: :post %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/submitted_proposals/_staff_discussion.html.erb
<div>
  <%= form_with(url: staff_discussion_submitted_proposal_path(@proposal), method: :post) do |f| %>
    <div class="mb-3">
      <h4>Discussion:</h4>
      <%=f.text_area(:discussion, required: true, size: '3x5', class:'form-control')%>
    </div>
    <button class="btn btn-primary">Submit</button>
  <% end %>
</div>
<br />
<div class="mt-4">
  <h2> Discussions </h2>
  <% @proposal.staff_discussions&.each do |staff| %>
    <div class="mb-3 row border m-1 p-1">
      <p><%= staff.discussion %></p>
    </div>
  <% end %>
</div>

app/views/submitted_proposals/index.html.erb
<main class="content">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        Proposals
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Dashboard", dashboards_path %> </a></li>
          <li class="breadcrumb-item active" aria-current="page"><%= link_to "Submitted Proposals", submitted_proposals_path %></li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="card" data-controller="submitted-proposals">
          <div class="card-header">
            <form class="form-inline">
              
              <div class="row">
                <div class="col-xs-6 col-md-3">
                  <label class="form-label">Keywords</label><br>
                  <input type="search" class="form-control" name="keywords" placeholder="Enter Keywords" value="<%= params[:keywords] %>">
                </div>
                <div class="col-xs-6 col-md-3">
                  <label class="form-label">Proposal Type</label><br>
                  <%= select_tag "proposal_type", options_for_select(all_proposal_types, params[:proposal_type]), { include_blank: '', class: 'form-control p-1' }%>
                </div>
                <div class="col-xs-6 col-md-3">
                  <label class="form-label">Status</label><br>
                  <%= select_tag :status, options_for_select(all_statuses, params[:status]), { include_blank: '', class: 'form-control p-1' } %>
                </div>
                <div class="col-xs-6 col-md-3">
                  <label class="form-label">Workshop Year</label><br>
                  <%= select_tag "workshop_year", options_for_select([[2021, 2021], [2022, 2022], [2023,2023], [2024, 2024], [2025, 2025], [2026, 2026], [2027, 2027], [2028, 2028], [2029, 2029]], params[:workshop_year]), { include_blank: '', class: 'form-control mb-3 p-1', style: 'width: 116px;'}%>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-6 col-md-6">
                  <label class="form-label">Subject Area</label><br>
                  <%= select_tag "subject_area", options_for_select(subjects_area, params[:subject_area]), { include_blank: '', class: 'form-control p-1' }%>
                </div>
                <div class="text-end col-xs-6 col-md-6">
                  <button class="btn btn-primary">Search</button>
                </div>
              </div>
            </form>
          </div>
          <div class="card-body"  style="background: #f4f7fc">
            <div class="col-12 col-lg-12">
              
              <div class="tab">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item col-6"><a class="nav-link active" href="#tab-1" data-bs-toggle="tab" role="tab">Submitted Proposals</a></li>

                  <li class="nav-item col-6"><a class="nav-link" href="#tab-2" data-bs-toggle="tab" role="tab">Demographic Data Graphs and charts</a></li>
                </ul>

                <div class="tab-content">
                  <div class="tab-pane active" id="tab-1" role="tabpanel">
                    <div class="text-end m-3">
                      <span data-action="click->submitted-proposals#editFlow" class="btn btn-primary">Send to EditFlow</span>
                      <%= link_to "Download CSV", download_csv_submitted_proposals_url( {:format => :csv}.merge(params.permit!)), class: "btn btn-primary" %>
                    </div>
                    <%= render partial: "proposals" %>
                  </div>
                  
                  <div class="tab-pane" id="tab-2" role="tabpanel">
                    <%= render partial: "demographic_charts" %>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>