config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  devise_scope :user do
    root to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  get :guidelines, to: 'pages#guidelines'
  resources :feedbacks, path: :feedback do
    member do
      patch :add_reply
    end
  end
  get 'dashboards', to: 'proposal_types#index'

  resources :submitted_proposals do
    collection do
      get :download_csv
      post :edit_flow
    end
    member do
      post :staff_discussion
      post :send_emails
      post :approve_status
      post :decline_status
    end
  end

  get :invite, to: 'invites#show'
  get 'expired' => 'invites#expired'
  post 'cancel' => 'invites#cancel'

  resources :proposals do
    post :latex, to: 'proposals#latex_input'
    member do
      get :rendered_proposal, to: 'proposals#latex_output'
      get :rendered_field, to: 'proposals#latex_field'
      patch :ranking
      get :locations
      post :upload_file
      post :remove_file
    end

    resources :invites, except: [:show] do
      member do
        post :inviter_response
        post :invite_reminder
        post :invite_email
      end
      collection do
        get :thanks
      end
    end
  end

  resources :survey do
    collection do
      get :survey_questionnaire
      get :faqs
      post :submit_survey
    end
  end

  resources :people, path: :person

  resources :submit_proposals do
    collection do
      get :thanks
    end
  end
  resources :proposal_types do
    resources :proposal_forms do
      member do
        post :clone
        delete :proposal_field
        get :proposal_field_edit
      end
      resources :proposal_fields do
        collection do
          post :latex_text
        end
      end
    end
    member do
      get :location_based_fields
      get :proposal_type_locations
    end
  end
  resources :locations do
    member do
      get :proposal_types
    end
  end
  resources :page_contents

  resources :faqs do
    member do
      patch :move
    end
  end

  get 'profile/' => 'profile#edit'
  patch 'update' => 'profile#update'
  post 'demographic_data' => 'profile#demographic_data'

  resources :roles do
    member do
      post :new_user
      post :new_role
      post :remove_role
    end
  end

  resources :subject_categories do
    resources :subjects
    resources :ams_subjects
  end

  resources :emails do
    collection do
      patch :email_template
    end
  end

  resources :email_templates
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_proposals, against: %i[title],
                                     associated_against: {
                                       people: %i[firstname lastname]
                                     }

  pg_search_scope :search_proposal_type, against: %i[proposal_type_id]
  pg_search_scope :search_proposal_status, against: %i[status]
  pg_search_scope :search_proposal_subject, against: %i[subject_id]
  pg_search_scope :search_proposal_year, against: %i[year]

  attr_accessor :is_submission

  has_many_attached :files
  has_many :proposal_locations, dependent: :destroy
  has_many :locations, -> { order 'proposal_locations.position' },
                          through: :proposal_locations
  belongs_to :proposal_type
  has_many :proposal_roles, dependent: :destroy
  has_many :people, through: :proposal_roles
  has_many(:answers, -> { order 'answers.proposal_field_id' },
                        inverse_of: :proposal, dependent: :destroy)
  has_many :invites, dependent: :destroy
  belongs_to :proposal_form
  has_many :proposal_ams_subjects, dependent: :destroy
  has_many :ams_subjects, through: :proposal_ams_subjects
  belongs_to :subject, optional: true
  has_many :staff_discussions, dependent: :destroy
  has_many :emails, dependent: :destroy

  validates :year, :title, presence: true, if: :is_submission
  validate :subjects, if: :is_submission
  validate :minimum_organizers, if: :is_submission
  validate :preferred_locations, if: :is_submission
  validate :not_before_opening, if: :is_submission
  before_save :create_code, if: :is_submission

  enum status: {
    draft: 0,
    submitted: 1,
    initial_review: 2,
    revision_requested: 3,
    revision_submitted: 4,
    in_progress: 5,
    decision_pending: 6,
    decision_email_sent: 7,
    approved: 8,
    declined: 9
  }

  scope :active_proposals, lambda {
    where(status: 'submitted')
  }

  scope :no_of_participants, lambda { |id, invited_as|
    joins(:invites).where('invites.invited_as = ?
      AND invites.proposal_id = ?', invited_as, id)
  }

  scope :submitted_type, lambda { |type|
    where(status: 1)
      .joins(:proposal_type).where(name: type)
  }

  def demographics_data
    DemographicData.where(person_id: invites.where(invited_as: 'Participant')
                   .pluck(:person_id))
  end

  def create_organizer_role(person, organizer)
    proposal_roles.create!(person: person, role: organizer)
  end

  def lead_organizer
    proposal_roles.joins(:role).find_by('roles.name = ?',
                                        'lead_organizer')&.person
  end

  def the_locations
    locations.pluck(:name).join(', ')
  end

  def list_of_organizers
    invites.where(invites: { invited_as: 'Organizer' }).map(&:person)
           .map(&:fullname).join(', ')
  end

  def supporting_organizers
    invites.where(invited_as: 'Organizer').where(response: %w[yes maybe])
  end

  def participants
    invites.where(invited_as: 'Participant').where(response: %w[yes maybe])
  end

  def participants_career(career)
    person_ids = participants.map(&:person_id)
    Person.where(id: person_ids).where(academic_status: career)
  end

  def self.to_csv
    attributes = ["Code", "Proposal Title", "Proposal Type", "Lead Organizer",
                  "Preffered Locations", "Status",
                  "Updated"]
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.find_each do |proposal|
        csv << [proposal.code, proposal.title, proposal.proposal_type.name,
                proposal.lead_organizer.fullname, proposal.the_locations,
                proposal.status, proposal.updated_at.to_date]
      end
    end
  end

  def pdf_file_type(file)
    file.content_type.in?(%w[application/pdf])
  end

  def macros
    preamble || ''
  end

  private

  def not_before_opening
    return unless DateTime.current.to_date > proposal_type.closed_date.to_date

    errors.add("Late submission - ", "proposal submissions are not allowed
               because of due date #{proposal_type.closed_date.to_date}".squish)
  end

  def minimum_organizers
    return unless invites.where(status: 'confirmed').count < 1

    errors.add('Supporting Organizers: ', 'At least one supporting organizer
               must confirm their participation by following the link in the
               email that was sent to them.'.squish)
  end

  def subjects
    errors.add('Subject Area:', "please select a subject area") if subject.nil?
    unless ams_subjects.pluck(:code).count == 2
      errors.add('AMS Subjects:', 'please select 2 AMS Subjects')
    end
  end

  def next_number
    codes = Proposal.submitted_type(proposal_type.name).pluck(:code)
    last_code = codes.reject { |c| c.to_s.empty? }.max

    return '001' if last_code.blank?

    (last_code[-3..].to_i + 1).to_s.rjust(3, '0')
  end

  def create_code
    return if code.present?

    tc = proposal_type.code || 'xx'
    self.code = year.to_s[-2..] + tc + next_number
  end

  def preferred_locations
    if locations.empty?
      errors.add('Preferred Locations:', "Please select at least one preferred
                 location".squish)
    end
  end
end

app/controllers/proposal_types_controller.rb
class ProposalTypesController < ApplicationController
  before_action :set_proposal_type,
                only: %i[show location_based_fields proposal_forms destroy update edit proposal_type_locations]

  def index
    @proposal_types = ProposalType.all
    redirect_to proposals_path and return unless current_user&.staff_member?
  end

  def new
    @proposal_type = ProposalType.new
  end

  def create
    @proposal_type = ProposalType.new(proposal_type_params)

    if @proposal_type.save
      redirect_to proposal_types_path, notice: 'Proposal Type successfully created'
    else
      redirect_to new_proposal_type_path(@proposal_type), alert: @proposal_type.errors.full_messages
    end
  end

  def edit; end

  def update
    if @proposal_type.update(proposal_type_params)
      redirect_to proposal_types_path, notice: 'Proposal Type successfully updated'
    else
      redirect_to edit_proposal_type_path(@proposal_type), alert: @proposal_type.errors.full_messages
    end
  end

  def destroy
    @proposal_type.destroy
    redirect_to proposal_types_path
  end

  def location_based_fields
    @proposal = Proposal.find(params[:proposal_id])
    @proposal_fields = @proposal.proposal_form&.proposal_fields&.where(location_id: params[:ids].split(","))
    @submission = session[:is_submission]
    render partial: 'proposal_forms/proposal_fields', locals: { proposal_fields: @proposal_fields }
  end

  def proposal_type_locations
    render json: @proposal_type.locations
  end

  def proposal_forms; end

  def show; end

  private

  def proposal_type_params
    params.require(:proposal_type).permit(:name, :year, :co_organizer, :participant, :code, :open_date, :closed_date,
                                          location_ids: [])
  end

  def set_proposal_type
    @proposal_type = ProposalType.find(params[:id])
  end
end

app/helpers/proposal_types_helper.rb
module ProposalTypesHelper
  def active_or_draft_form?(id)
    proposal_type = ProposalType.find(id)
    proposal_type.proposal_forms.where(status: %i[active draft]).present?
  end

  def list_proposal_locations(proposal_type)
    return '' if proposal_type.locations.empty?

    proposal_type.locations.map(&:name).join("<br>\n").html_safe
  end
end

app/views/proposal_types/_form.html.erb
<main class="content">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        Proposal Type
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"> <%= link_to "Dashboard", dashboards_path %> </li>
          <li class="breadcrumb-item"> <%= link_to "Proposal Types", proposal_types_path %> </li>
          <% if @proposal_type.new_record? %>
            <li class="breadcrumb-item active" aria-current="page">New</li>
          <% else %>
             <li class="breadcrumb-item active" aria-current="page">Edit</li>
          <% end %>
        </ol>
      </nav>
    </div>
    <div class="col-10">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title" id="proposal_type_head_name"><%= @proposal_type.name %></h5>
        </div>
        <div class="card-body">
          <%= form_for @proposal_type do |f| %>
          <div class="mb-3">
            <%= f.label :name , class: 'form-label' %><br>
            <%= f.text_field :name %>
          </div>

          <div class="mb-3">
            <%= f.label :code, class: 'form-label' %><br>
            <%= f.text_field :code %>
          </div>

          <div class="mb-3">
            <%= f.label :year, class: 'form-label' %><br>
            <%= f.text_field :year, class: 'form-control' %>
            <small>This text field supports a list of years i.e. 2021, 2022..</small>
          </div>

          <div class="mb-3">
            <%= f.label :'Open Date', class: 'form-label' %>
            <%= f.text_field :open_date, class: 'form-control', type: 'date', value: @proposal_type.open_date&.to_date %>
          </div>

          <div class="mb-3">
            <%= f.label :'Closed Date', class: 'form-label' %>
            <%= f.text_field :closed_date, class: 'form-control', type: 'date', value: @proposal_type.closed_date&.to_date %>
          </div>

          <div class="mb-3">
            <%= f.label :'Maximum number of Co-organizers' , class: 'form-label' %><br>
            <%= f.number_field :co_organizer %>
          </div>

          <div class="mb-3">
            <%= f.label :'Maximum number of Participants', class: 'form-label' %><br>
            <%= f.number_field :participant %>
          </div>

          <div class="mb-3">
            <%= f.label :Location , class: 'form-label' %><br>
            <%= f.select :location_ids, locations, {}, class: 'form-control', multiple: true %>
          </div>
          <%= f.submit @proposal_type.new_record? ? "Create Proposal Type" : "Update Proposal Type", class:  'btn btn-primary' %>
          <%= link_to "Back", proposal_types_path, class: 'btn btn-primary  '%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/proposal_types/edit.html.erb
<%= render 'form', proposal_type: @proposal_type %>

app/views/proposal_types/index.html.erb
<main class="content" data-controller="proposal-types">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        Proposal Types
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"> <%= link_to "Dashboard", dashboards_path %> </li>
          <li class="breadcrumb-item active" aria-current="page">Proposal Types</li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <%= link_to "Create Proposal Type", new_proposal_type_path, class: 'btn btn-primary' %>
          </div>
          <table class="table">
            <thead>
              <tr>
                <th style="width:40%;">Name</th>
                <th>Locations</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @proposal_types.each do |proposal_type|%>                     
                <tr>
                  <td><%= proposal_type.name %></td>
                  <td><%= list_proposal_locations(proposal_type) %></td>
                  <td class="table-action">
                    <%= link_to '<i class="align-middle fas fa-fw fa-pen" data-toggle="tooltip" title="Edit"></i>Edit'.html_safe, edit_proposal_type_path(proposal_type) %>
                    <%= link_to '<i class="align-middle fas fa-fw fa-trash" data-toggle="tooltip" title="Delete" ></i>Delete'.html_safe, proposal_type_path(proposal_type), method: :delete ,
                      data: {confirm: "Are you sure you want to delete #{proposal_type.name}?"} %>
                    <%= link_to 'Proposal forms',  proposal_type_proposal_forms_path(proposal_type_id: proposal_type), class: 'btn btn-pill btn-primary text-white'%>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/proposal_types/new.html.erb
<%= render 'form', proposal_type: @proposal_type %>

app/views/proposal_types/proposal_forms.html.erb
<main class="content">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        Proposal Forms
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Dashboard", dashboards_path %></li>
          <li class="breadcrumb-item"><%= link_to "Proposal Types", proposal_types_path %> </li>
          <li class="breadcrumb-item active" aria-current="page"> <%= @proposal_type.name %></li>
          <li class="breadcrumb-item active" aria-current="page">Proposal Forms</li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            </h6>
          </div>
          <div class="me-3" data-controller="proposal-types">
            <div class="float-end">
              <a data-toggle="tooltip" title="Clone" data-bs-toggle="modal" data-bs-target="#cloneProposalForm<%= @proposal_type.id %>" href="#" class="btn btn-pill btn-primary text-white">
                <i class="align-middle fas fa-fw fa-copy cursor-pointer "></i>Clone
              </a>
              <%= link_to 'Create Proposal form',  new_proposal_form_url(proposal_type_id: @proposal_type.id), class: 'btn btn-pill btn-primary text-white', data: (active_form?(@proposal_type.id) ? {confirm: 'You have already active proposal form. If you continue already active forms will become inactive'} : '') %>
              <%= render partial: 'proposal_forms/clone_proposal_form', locals: { proposal_type_id: @proposal_type.id } %>
            </div>
          </div>
          <table class="table">
            <thead>
              <tr>
                <th>Versions</th>
                <th>Location </th>
                <th>Status</th>
                <th>Created at</th>
                <th>Created by</th>
                <th>Updated by</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @proposal_type.proposal_forms.each do |proposal_form| %>
              <tr>
                <td><%= proposal_form.version %></td>
                <td>
                  <% proposal_form.proposal_type.locations.each do |loc| %>
                   <%= loc.name %><br>
                  <% end %>
                </td>
                <td><%= proposal_form.status %></td>
                <td><%= proposal_form.created_at.to_date %></td>
                <td><%= proposal_form.created_by&.email %></td>
                <td><%= proposal_form.updated_by&.email %></td>
                <td class="table-action">
                  <%= link_to '<i class="align-middle fas fa-fw fa-eye" data-toggle="tooltip" title="Show"></i>Show'.html_safe, proposal_form_path(proposal_form) %>
                  <% if proposal_form.draft? || proposal_form.active? %>
                   <%= link_to '<i class="align-middle fas fa-fw fa-pen" data-toggle="tooltip" title="Edit"></i>Edit'.html_safe, edit_proposal_form_path(proposal_form, proposal_type_id: @proposal_type.id) %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>