config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  devise_scope :user do
    root to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  get :guidelines, to: 'pages#guidelines'
  resources :feedbacks, path: :feedback do
    member do
      patch :add_reply
    end
  end
  get 'dashboards', to: 'proposal_types#index'

  resources :submitted_proposals do
    collection do
      get :download_csv
      post :edit_flow
    end
    member do
      post :staff_discussion
      post :send_emails
      post :approve_status
      post :decline_status
    end
  end

  get :invite, to: 'invites#show'
  get 'expired' => 'invites#expired'
  post 'cancel' => 'invites#cancel'

  resources :proposals do
    post :latex, to: 'proposals#latex_input'
    member do
      get :rendered_proposal, to: 'proposals#latex_output'
      get :rendered_field, to: 'proposals#latex_field'
      patch :ranking
      get :locations
      post :upload_file
      post :remove_file
    end

    resources :invites, except: [:show] do
      member do
        post :inviter_response
        post :invite_reminder
        post :invite_email
      end
      collection do
        get :thanks
      end
    end
  end

  resources :survey do
    collection do
      get :survey_questionnaire
      get :faqs
      post :submit_survey
    end
  end

  resources :people, path: :person

  resources :submit_proposals do
    collection do
      get :thanks
    end
  end
  resources :proposal_types do
    resources :proposal_forms do
      member do
        post :clone
        delete :proposal_field
        get :proposal_field_edit
      end
      resources :proposal_fields do
        collection do
          post :latex_text
        end
      end
    end
    member do
      get :location_based_fields
      get :proposal_type_locations
    end
  end
  resources :locations do
    member do
      get :proposal_types
    end
  end
  resources :page_contents

  resources :faqs do
    member do
      patch :move
    end
  end

  get 'profile/' => 'profile#edit'
  patch 'update' => 'profile#update'
  post 'demographic_data' => 'profile#demographic_data'

  resources :roles do
    member do
      post :new_user
      post :new_role
      post :remove_role
    end
  end

  resources :subject_categories do
    resources :subjects
    resources :ams_subjects
  end

  resources :emails do
    collection do
      patch :email_template
    end
  end

  resources :email_templates
end

app/models/proposal_form.rb
class ProposalForm < ApplicationRecord
  validates :title, presence: true
  belongs_to :proposal_type
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'
  has_many(:proposal_fields,
           -> { order(position: :asc) },
           inverse_of: :proposal_form, dependent: :destroy)
  enum status: { draft: 0, active: 1, inactive: 2 }

  scope :active_form, ->(id) { where(proposal_type_id: id, status: :active)&.last }
  default_scope { order(created_at: :desc) }
end

app/models/proposal_type.rb
class ProposalType < ApplicationRecord
  validates :name, :participant, :co_organizer, :code, :open_date, :closed_date, presence: true
  validates :code, uniqueness: true
  has_many :proposals, dependent: :destroy
  has_many :proposal_forms, dependent: :destroy
  has_many :proposal_type_locations, dependent: :destroy
  has_many :locations, through: :proposal_type_locations
  validate :not_closed_date_greater

  scope :active_forms, -> { joins(:proposal_forms).where('proposal_forms.status =?', 1).distinct }

  def active_form
    proposal_forms.where('proposal_forms.status =?', 1).last
  end

  def not_lead_organizer?(person_id)
    proposals.joins(proposal_roles: :role)
             .where("proposal_roles.person_id =?", person_id)
             .where('roles.name =?', 'lead_organizer').empty?
  end

  # rubocop:disable Metrics/AbcSize
  def not_closed_date_greater
    return if open_date.nil? || closed_date.nil?

    if open_date.to_date > closed_date.to_date
      errors.add("Open Date ", "#{open_date.to_date} - cannot be greater than
          Closed Date #{closed_date.to_date}".squish)
    elsif open_date.to_date == closed_date.to_date
      errors.add("Open Date ", "#{open_date.to_date} - cannot be same as
          Closed Date #{closed_date.to_date}".squish)
    end
  end
  # rubocop:enable Metrics/AbcSize
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: %w[show edit destroy ranking locations]
  before_action :set_careers, only: %w[show edit]
  before_action :authenticate_user!

  def index
    @proposals = current_user&.person&.proposals
  end

  def ranking
    @proposal_locations = @proposal.proposal_locations
                                   .find_by(location_id: params[:location_id])
    @proposal_locations.update(position: params[:position].to_i)
    head :ok
  end

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = start_new_proposal
    limit_of_one_per_type and return unless no_proposal?

    if @proposal.save
      @proposal.create_organizer_role(current_user.person, organizer)
      redirect_to edit_proposal_path(@proposal), notice: "Started a new
                              #{@proposal.proposal_type.name} proposal!".squish
    else
      redirect_to new_proposal_path, alert: @proposal.errors
    end
  end

  def show; end

  def edit
    @proposal.invites.build
  end

  def locations
    render json: @proposal.locations, status: :ok
  end

  # POST /proposals/:1/latex
  def latex_input
    proposal_id = latex_params[:proposal_id]
    session[:proposal_id] = proposal_id

    input = latex_params[:latex]
    ProposalPdfService.new(proposal_id, latex_temp_file, input).pdf

    head :ok
  end

  # GET /proposals/:id/rendered_proposal.pdf
  def latex_output
    proposal_id = params[:id]
    ProposalPdfService.new(proposal_id, latex_temp_file, 'all').pdf

    @proposal = Proposal.find_by(id: proposal_id)
    @year = @proposal&.year || Date.current.year.to_i + 2

    fh = File.open("#{Rails.root}/tmp/#{latex_temp_file}")
    @latex_infile = fh.read

    render_latex
  end

  # rubocop:disable Metrics/AbcSize
  # GET /proposals/:id/rendered_field.pdf
  def latex_field
    prop_id = params[:id]
    return if prop_id.blank?

    @proposal = Proposal.find_by(id: prop_id)
    @year = @proposal&.year || Date.current.year.to_i + 2

    fh = File.open("#{Rails.root}/tmp/#{latex_temp_file}")
    @latex_infile = fh.read
    @latex_infile = LatexToPdf.escape_latex(@latex_infile) if @proposal.no_latex

    render_latex
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html do
        redirect_to proposals_url, notice: "Proposal was successfully deleted."
      end
      format.json { head :no_content }
    end
  end

  def upload_file
    @proposal = Proposal.find(params[:id])
    params[:files].each do |file|
      if @proposal.pdf_file_type(file)
        @proposal.files.attach(file)
        render json: "File successfully uploaded", status: :ok
      else
        render json: "File format not supported", status: :bad_request
      end
    end
  end

  def remove_file
    @proposal = Proposal.find(params[:id])
    file = @proposal.files.where(id: params[:attachment_id])
    file.purge_later

    flash[:notice] = 'File has been removed!'

    if request.xhr?
      render js: "window.location='#{edit_proposal_path(@proposal)}'"
    else
      redirect_to edit_proposal_path(@proposal)
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:proposal_type_id, :title, :year)
  end

  def organizer
    Role.find_or_create_by!(name: 'lead_organizer')
  end

  def set_proposal
    @proposal = Proposal.find_by(id: params[:id])
    @submission = session[:is_submission]
  end

  def latex_params
    params.permit(:latex, :proposal_id, :format)
  end

  def start_new_proposal
    prop = Proposal.new(proposal_params)
    prop.status = :draft
    prop.proposal_form = ProposalForm.active_form(prop.proposal_type_id)
    prop
  end

  def no_proposal?
    @proposal.proposal_type.not_lead_organizer?(current_user.person)
  end

  def limit_of_one_per_type
    redirect_to new_proposal_path, alert: "There is a limit of one
      #{@proposal.proposal_type.name} proposal per lead organizer.".squish
  end

  def latex_temp_file
    proposal_id = latex_params[:proposal_id] || params[:id]
    "propfile-#{current_user.id}-#{proposal_id}.tex"
  end

  def render_latex
    # rubocop:disable all
    latex = @proposal.macros + "\n\\begin{document}\n" + @latex_infile.to_s
    render layout: "application", inline: latex, formats: [:pdf]
  rescue ActionView::Template::Error => e
    flash[:alert] = "There are errors in your LaTeX code. Please see the
                        output from the compiler, and the LaTeX document,
                        below".squish
    error_output = ProposalPdfService.format_errors(e)
    render layout: "latex_errors", inline: error_output.to_s, formats: [:html]
    # rubocop:enable all
  end

  def set_careers
    @careers = Person.where(id: @proposal.participants.pluck(:person_id))
                     .pluck(:academic_status)
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
  def proposal_types
    today = DateTime.now
    proposal_type = ProposalType.active_forms.where('open_date <= ?', today)
    today = today.to_date
    proposal_type = proposal_type.where('closed_date >= ?', today)
    proposal_type.map { |pt| [pt.name, pt.id] }
  end

  def no_of_participants(id, invited_as)
    Invite.where('invited_as = ? AND proposal_id = ?', invited_as, id)
  end

  def proposal_type_year(proposal_type)
    return [Date.current.year + 2] if proposal_type.year.blank?

    proposal_type.year&.split(",")&.map { |year| year }
  end

  def locations
    Location.all.map { |loc| [loc.name, loc.id] }
  end

  def all_proposal_types
    ProposalType.all.map { |pt| [pt.name, pt.id] }
  end

  def all_statuses
    Proposal.statuses.map { |k, v| [k.humanize.capitalize, v] }
  end

  def common_proposal_fields(proposal)
    proposal.proposal_form&.proposal_fields&.where(location_id: nil)
  end

  def proposal_roles(proposal_roles)
    proposal_roles.joins(:role).where(person_id: current_user.person&.id).pluck('roles.name').map(&:titleize).join(', ')
  end

  def lead_organizer?(proposal_roles)
    proposal_roles.joins(:role).where('person_id =? AND roles.name =?', current_user.person&.id,
                                      'lead_organizer').present?
  end

  def proposal_ams_subjects_code(proposal, code)
    proposal.proposal_ams_subjects.find_by(code: code)&.ams_subject_id
  end

  # rubocop:disable Rails/OutputSafety
  def organizer_intro(proposal)
    types_with_intro = ['5 Day Workshop', 'Summer School']
    return '' unless types_with_intro.include? proposal.proposal_type.name

    "<p>5-Day Workshops and Summer Schools require a minimum of 2, and a maximum
     of 4 total organizers per proposal. In accordance with BIRS' commitment to
     equity, diversity and inclusion (EDI), the organizing committee should
     contain at least one early-career researcher within ten years of their
     doctoral degree. For applications with two organizers, at least one member
     of the organizing committee must be from an under-represented community in
     STEM disciplines. For applications with three or more organizers, at least
     two members of the organizing committee must be from an under-represented
     community in STEM disciplines.</p>".html_safe
  end
  # rubocop:enable Rails/OutputSafety

  def existing_organizers(invite)
    organizers = invite.proposal.list_of_organizers.remove(invite.person&.fullname)
    organizers.prepend(" and ") if organizers.present?
    organizers.strip.delete_suffix(",")
  end

  def invite_status(response, status)
    return "Invite has been cancelled" if status == 'cancelled'

    case response
    when "yes", "maybe"
      "Invitation accepted"
    when nil
      "Not yet responded to invitation"
    when "no"
      "Invitation declined"
    end
  end

  def proposal_status(status)
    return "submitted" if %w[approved declined].include?(status)

    status&.split('_')&.map(&:capitalize)&.join(' ')
  end

  def proposal_status_class(status)
    proposals = {
      "approved" => "text-approved",
      "declined" => "text-declined",
      "draft" => "text-muted",
      "submitted" => "text-proposal-submitted",
      "initial_review" => "text-warning",
      "revision_requested" => "text-danger",
      "revision_submitted" => "text-revision-submitted",
      "in_progress" => "text-success",
      "decision_pending" => "text-info",
      "decision_email_sent" => "text-primary"
    }
    proposals[status]
  end

  def invite_response_color(status)
    case status
    when "yes", "maybe"
      "text-success"
    when nil
      "text-primary"
    when "no"
      "text-danger"
    end
  end

  def invite_deadline_date_color(invite)
    'text-danger' if invite.status == 'pending' && invite.deadline_date.to_date < DateTime.now.to_date
  end

  def graph_data(param, param2, proposal)
    citizenships = proposal.demographics_data.pluck(:result).pluck(param, param2).flatten.reject do |s|
      s.blank? || s.eql?("Other")
    end
    data = Hash.new(0)

    citizenships.each do |c|
      data[c] += 1
    end
    data
  end

  def nationality_data(proposal)
    graph_data("citizenships", "citizenships_other", proposal)
  end

  def ethnicity_data(proposal)
    graph_data("ethnicity", "ethnicity_other", proposal)
  end

  def gender_labels(proposal)
    data = graph_data("gender", "gender_other", proposal)
    data.keys
  end

  def gender_values(proposal)
    data = graph_data("gender", "gender_other", proposal)
    data.values
  end

  # rubocop:disable Metrics/AbcSize
  def career_data(param, param2, proposal)
    person = Person.where.not(id: proposal.lead_organizer.id)
    career_stage = person.where(id: proposal.invites.where(invited_as:
      'Participant').pluck(:person_id)).pluck(param, param2).flatten.reject do |s|
      s.blank? || s.eql?("Other")
    end
    data = Hash.new(0)

    career_stage.each do |s|
      data[s] += 1
    end
    data
  end
  # rubocop:enable Metrics/AbcSize

  def career_labels(proposal)
    data = career_data("academic_status", "other_academic_status", proposal)
    data.keys
  end

  def career_values(proposal)
    data = career_data("academic_status", "other_academic_status", proposal)
    data.values
  end

  def stem_graph_data(proposal)
    citizenships = proposal.demographics_data.pluck(:result).pluck("stem").flatten.reject do |s|
      s.blank? || s.eql?("Other")
    end
    data = Hash.new(0)

    citizenships.each do |c|
      data[c] += 1
    end
    data
  end

  def stem_labels(proposal)
    data = stem_graph_data(proposal)
    data.keys
  end

  def stem_values(proposal)
    data = stem_graph_data(proposal)
    data.values
  end
end

app/views/proposals/_confirm_participant.html.erb
<% confirmed_participants.each do |participant| %>
  <div class="mb-3 row border m-1">
    <div class="col-6 mt-2">
      <div class="mb-3">
        <label for="firstname">First Name: </label>
        <label for="firstname"><%= participant.firstname %></label>
      </div>
      <div class="mb-3">
        <label for="lastname">Last Name: </label>
        <label for="lastname"><%= participant.lastname %></label>
      </div>
      <div class="mb-3">
        <label for="email">Email: </label>
        <label for="email"><%= participant.email %></label>
      </div>
    </div>
    <div class="col-6 mt-2">
      <div class="mb-3">
        <% if participant.affiliation.present? %>
          <div class="mb-3">
            <label>Affiliation: </label>
            <label><%= participant.affiliation %></label>
          </div>
        <% end %>
      </div>
      <div class="mb-3">
        <div class="mb-3">
          <label>Career Stage: </label>
          <% if participant.academic_status.present? && participant.academic_status != "Other" %>
            <label><%= participant.academic_status %></label>
          <% else %>
            <label><%= participant.other_academic_status %></label>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/proposals/_email_preview.html.erb
<div class="modal fade" id="email-preview" tabindex="-1" aria-labelledby="email-previewLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= "BIRS Proposal: Invite for " %><span id="invited_as_title"></span></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body m-3">
        <h1>Dear < Firstname Lastname></h1>
          <p>
          <%= @proposal.lead_organizer&.fullname %> is putting together a proposal for a <%= @proposal.proposal_type.name %> titled "<%= @proposal.title %>" for submission to the Banff International Research Station. If successful, the program would take place at some time during the 2023 calendar year.
        </p>
        <p>
          This invitation is intended to gauge your interest in being a <span id="invited_as_pre"></span> for this proposed workshop, provided that it is accepted and that the dates work with your schedule. Your response would help the organizing committee and the BIRS review committee determine the appeal of this proposed workshop to the wider mathematical community.
        </p>
        <p>
          Kindly indicate your response at the link below:
        </p>
        <p><%= link_to 'Click here', '#' %></p>
        <p>Thank you for considering this request!</p>
        <p>Banff International Research Station,<br>
            and the organizing committee.</p>
      </div>
      <div class="modal-footer" data-controller="nested-invites">
        <button data-action="click->nested-invites#sendInvite" data-id="<%= @proposal.id %>" class="btn btn-secondary" data-organizer="<%= no_of_participants(@proposal.id, 'Organizer').last&.id %>"
        data-participant="<%= no_of_participants(@proposal.id, 'Participant').last&.id %>">Send Invitation</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/proposals/_invite.html.erb
<div class="nested-invites-wrapper" data-new-record="<%= f.object&.new_record? %>" >
  <div class="row">
    <div class="mb-3 col-md-6">
      <label class="required" for="firstname">First Name</label>
      <input type="text" name="invites_attributes[NEW_RECORD][firstname]"
        class="form-control" 
        id="<%=  invited_as.downcase %>_firstname"
        data-role="<%= invited_as.downcase %>"
        data-action="change->proposal-form#disableOtherInvites"
      >
    </div>
    <div class="mb-3 col-md-6">
      <label for="lastname" class="required">Last Name</label>
      <input type="text" name="invites_attributes[NEW_RECORD][lastname]" 
        class="form-control" id="<%=  invited_as.downcase %>_lastname"
        data-role="<%= invited_as.downcase %>"
        data-action="change->proposal-form#disableOtherInvites"
      >
    </div>
  </div>

  <div class="row">
    <div class="mb-3 col-md-6">
      <label for="email" class="required">Email</label>
      <input type="email" name="invites_attributes[NEW_RECORD][email]" 
        class="form-control" id="<%=  invited_as.downcase %>_email"
        data-role="<%= invited_as.downcase %>"
        data-action="change->proposal-form#disableOtherInvites"
      >
    </div>
    <div class="mb-3 col-md-6">
      <label for="deadline" class="required">Deadline for reply</label>
      <input type="date" name="invites_attributes[NEW_RECORD][deadline_date]" 
        class="form-control" id="<%= invited_as.downcase %>_deadline"
        value="<%= date %>"
        data-action="click->proposal-form#presentDate"
      >
    </div>
  </div>

  <input type="hidden" name="invites_attributes[NEW_RECORD][invited_as]" 
    value="<%= invited_as %>" id="<%= invited_as.downcase %>_invited_as"
    data-role="<%= invited_as.downcase %>"
    data-action="change->proposal-form#disableOtherInvites"
  >
</div>

app/views/proposals/_lead_organizer.html.erb
<h3>Lead Organizer</h3>
<div class="mb-3 row border m-1 p-1">
  <div class="col-6 mt-2">
    <div class="mb-3">
      <label for="firstname">First Name: </label>
      <label for="firstname"><%= @proposal.lead_organizer.firstname %></label>
    </div>
    <div class="mb-3">
      <label for="lastname">Last Name: </label>
      <label for="lastname"><%= @proposal.lead_organizer.lastname %></label>
    </div>
    <div class="mb-3">
      <label for="email">Email: </label>
      <label for="wmail"><%= @proposal.lead_organizer.email %></label>
    </div>
    <% if @proposal.lead_organizer.affiliation.present? %>
      <div class="mb-3">
        <label>Affiliation: </label>
        <label><%= @proposal.lead_organizer.affiliation %></label>
      </div>
    <% end %>
  </div>
</div>

app/views/proposals/_organizer.html.erb
<div class="mb-3 row border m-1">
  <div class="col-6 mt-2">
    <div class="mb-3">
      <label for="firstname">First Name: </label>
      <label for="firstname"><%= invite.firstname %></label>
    </div>
    <div class="mb-3">
      <label for="lastname">Last Name: </label>
      <label for="lastname"><%= invite.lastname %></label>
    </div>
    <div class="mb-3">
      <label for="email">Email: </label>
      <label for="email"><%= invite.email %></label>
    </div>
    <% if invite.person.affiliation.present? %>
      <div class="mb-3">
        <label>Affiliation: </label>
        <label><%= invite.person.affiliation %></label>
      </div>
    <% end %>
    <% if invite.invited_as == 'Participant' && invite.person.academic_status.present? %>
      <div class="mb-3">
        <label>Academic Status: </label>
        <label><%= invite.person.academic_status %></label>
      </div>
    <% end %>
  </div>
  <div class="col-6 mt-2">
    <div class="mb-3">
      <label for="status">Status: </label>
      <label for="status" class=<%= invite_response_color(invite.response) %> ><%= invite_status(invite.response, invite.status) %></label>
    </div>
    <div class="mb-3">
      <label for="created_at">Invitation Date: </label>
      <label for="created_at"><%= invite.created_at.to_date %></label>
    </div>
    <div class="mb-3 <%= invite_deadline_date_color(invite) %>">
      <label for="deadline_date">Deadline Date: </label>
      <label for="deadline_date"><%= invite.deadline_date.to_date %></label>
    </div>
    <div class="float-end mb-3">
      <% if invite.pending? %>
        <%= link_to 'Cancel Invite', cancel_url(code: invite.code), class: 'btn btn-sm btn-primary', method: :post %>
        <%= link_to 'Invite Reminder', invite_reminder_proposal_invite_url(invite.proposal, invite, code: invite.code), class: 'btn btn-sm btn-primary', method: :post %>
      <% end %>
    </div>
  </div>
</div>

app/views/proposals/edit.html.erb
<%= render 'email_preview' %>
<%= render 'proposal', proposal: @proposal %>

app/views/proposals/index.html.erb
<main class="content">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        Proposals
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Dashboard", dashboards_path %> </a></li>
          <li class="breadcrumb-item active" aria-current="page"><%= link_to "Proposals", proposals_path %></li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            </h6>
          </div>
          <table class="table">
            <thead>
              <tr>
                <th>Code</th>
                <th>Proposal Title</th>
                <th>Proposal Type</th>
                <th>Role</th>
                <th>Preferred Location</th>
                <th>Status</th>
                <th width="125">Updated</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @proposals&.each do |proposal| %>
              <tr>
                <td><%= proposal.code %></td>
                <td><%= proposal.title %></td>
                <td><%= proposal.proposal_type.name %></td>
                <td><%= proposal_roles(proposal.proposal_roles) %></td>
                <td> 
                  <% proposal.locations.each do |loc| %>
                   <%= loc.name %><br>
                  <% end %>
                </td>
                <td class=<%= proposal_status_class(proposal.status) %> >
                  <%= proposal_status(proposal.status) %>
                </td>
                <td><%= proposal.updated_at.to_date %></td>
                <td class="table-action">
                  <%= link_to '<i class="align-middle fas fa-fw fa-eye"></i>Show'.html_safe, proposal_url(proposal) %>
                  <% if lead_organizer?(proposal.proposal_roles) %>
                    <% unless proposal.submitted? || proposal.revision_submitted? || proposal.approved? || proposal.declined? %>
                     <%= link_to '<i class="align-middle fas fa-fw fa-pen"></i>Edit'.html_safe, edit_proposal_path(proposal) %>
                    <% end %>
                    <%= link_to '<i class="align-middle fas fa-fw fa-trash"></i>Delete'.html_safe, proposal_path(proposal), method: :delete ,
                      data: {confirm: "Are you sure you want to delete #{proposal.proposal_type.name}?"} %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/proposals/new.html.erb
<main class="content">
  <div class="container-fluid">
    <div class="header">
      <h1 class="header-title">
        Proposals
      </h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
           <li class="breadcrumb-item"> <%= link_to "Dashboard", dashboards_path %> </a></li>
          <li class="breadcrumb-item active" aria-current="page"><%= link_to "Proposals", proposals_path %></li>
          <li class="breadcrumb-item active" aria-current="page">New</li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <div data-controller="submit-proposals">  
              <%= form_for @proposal do  |f| %>
                <div class="col-lg-8">
                  <div class="mb-3">
                    <%= f.label :proposal_types, "Select the type of proposal:", class: 'form-label' %>
                    <%= f.select :proposal_type_id, options_for_select(proposal_types), {}, class: 'form-select w-50' %>
                  </div>
                  <div class="form-group">
                    <%= f.submit 'Submit', class:'btn btn-primary' %>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/proposals/rendered-proposal.pdf.erb
<%= raw @latex_input %>

app/views/proposals/show.html.erb
<%= render 'proposal', proposal: @proposal %>